Implement CheckCollisionRay2dPoly() function
raylib-extras/extras-c pull request #5
Opened 2023-08-05 05:51 UTC by jdeokkim

This pull requests implements `CheckCollisionRay2dPoly()` function for `ray_collision_2d.h`, which checks collision between a ray and a polygon.

Below is an example code that utilizes this function.

![...](https://github.com/raylib-extras/extras-c/assets/28700668/5678e8d3-da15-42c0-b180-ef2076cdc875)

```c
/* Includes =========================================================================== */

#include "raylib.h"

#define RAY2D_COLLISION_IMPLEMENTATION
#include "external/ray_collision_2d.h"

/* Macros ============================================================================= */

#define TARGET_FPS     60

#define SCREEN_WIDTH   800
#define SCREEN_HEIGHT  600

#define MAX_RAY_COUNT  256

/* Private Function Prototypes ======================================================== */

static void DrawPolygon(Vector2 *points, int pointCount, Color color);

/* Public Functions =================================================================== */

int main(void) {
    SetConfigFlags(FLAG_MSAA_4X_HINT);
    
    InitWindow(SCREEN_WIDTH, SCREEN_HEIGHT, "...");

    SetTargetFPS(TARGET_FPS);

    Vector2 points[] = {
        { 300.0f, 100.0f },
        { 500.0f, 100.0f },
        { 500.0f, 500.0f },
        { 400.0f, 200.0f }
    };

    const int pointCount = sizeof points / sizeof *points;

    while (!WindowShouldClose()) {
        BeginDrawing();
            
        ClearBackground(BLACK);

        Ray2d ray;

        {
            ray.Origin = GetMousePosition();

            for (int i = 0; i < MAX_RAY_COUNT; i++) {
                ray.Direction = Vector2Rotate(
                    (Vector2) { .x = 2.0f * SCREEN_WIDTH },
                    (i + 1) * (DEG2RAD * (360.0f / MAX_RAY_COUNT))
                );

                Vector2 intersect;

                bool result = CheckCollisionRay2dPoly(ray, points, pointCount, &intersect);

                if (!result) intersect = Vector2Add(ray.Origin, ray.Direction);

                DrawLineEx(
                    ray.Origin,
                    intersect,
                    1.0f,
                    ColorAlpha(WHITE, 0.75f)
                );
            }
        }

        DrawCircleV(ray.Origin, 4.0f, ColorAlpha(WHITE, 0.85f));

        DrawPolygon(points, pointCount, GREEN);

        DrawFPS(8, 8);

        EndDrawing();
    }

    CloseWindow();

    return 0;
}

/* Private Functions ================================================================== */

static void DrawPolygon(Vector2 *points, int pointCount, Color color) {
    for (int j = pointCount - 1, i = 0; i < pointCount; j = i, i++)
        DrawLineEx(points[j], points[i], 2.0f, color);
}
```

2023-08-05 14:44 UTC, JeffM2501 requested changes
The code looks fine, but I would like some changes to make the file more consistent.

2023-08-05 14:44 UTC, JeffM2501 commented on ray_collision_2d.h
> +*   Copyright (c) 2023 Jaedeok Kim
I would prefer you simply state what function you made, and not make it look like you are claiming copyright on the entire file.

2023-08-05 14:44 UTC, JeffM2501 commented on ray_collision_2d.h
> +		if (points == NULL || pointCount < 3) {
Please follow the same styles as the rest of the file.

2023-08-05 14:44 UTC, JeffM2501 commented on ray_collision_2d.h
> +	} Ray2d;
Please follow the same styles as the rest of the file.

2023-08-05 14:44 UTC, JeffM2501 commented on ray_collision_2d.h
> +		}
this should probably be it's own line/line intersection function so it's reusable

2023-08-06 16:45 UTC, JeffM2501 commented on ray_collision_2d.h
> +
why not just call fmax and fmin for everyone? I'm not a fan of having more C++exceptions.

2023-08-06 16:46 UTC, JeffM2501 commented on ray_collision_2d.h
> +	bool CheckCollisionRay2ds(Ray2d ray1, Ray2d ray2, float* length);
This should be called CheckCollisionRay2dRay2d so that it fits the format of the other functions (ray vs whatever it hits).
I also wonder if this should return the intersect?

2023-08-06 16:47 UTC, JeffM2501 commented on ray_collision_2d.h
> +		}
spacing is odd here.

2023-08-08 14:30 UTC, jdeokkim commented
Could you let me know if there are any changes required for my current code?

2023-08-12 02:55 UTC, JeffM2501 approved these changes

2023-08-12 02:55 UTC, merged

2023-08-12 02:56 UTC, JeffM2501 commented
Thanks for the addition

2023-08-12 03:29 UTC, jdeokkim commented
Thank you very much!!