Added transform 2d header and sample
raylib-extras/extras-c pull request #6
Opened 2023-08-07 23:33 UTC by Smiley98

I've made a sample project to illustrate the added functionality. Please let me know if I need to make any changes!

2023-08-12 02:57 UTC, JeffM2501 commented on transform_2d.h
> +// define RAY2D_TRANSFORM_IMPLEMENTATION in one and only one c/cpp files
this does not match the define used below
TRANSFORM2D_IMPLEMENTATION

2023-08-12 02:57 UTC, JeffM2501 commented on transform_2d.h
> +#endif
files need to end in a newline

2023-08-12 02:59 UTC, JeffM2501 commented on transform_2d/samples/example.c
> +	return 0;
spacing is incorrect

2023-08-12 02:59 UTC, JeffM2501 commented on transform_2d/samples/example.c
> +        EndDrawing();
Please add some newlines here to space out the code, it's not clear what is happening

2023-08-12 03:00 UTC, JeffM2501 requested changes
I'm not sure how useful this is to just transform points. I think this should have functions to set the GL matrix and push and pop, just like the C++ 3d object transform has.

The utility of this would be improved by making it support nested transforms too.

2023-08-16 15:33 UTC, Smiley98 commented
Thanks for the feedback, I'll take a look at the matrix stack in the context of 2d and run my proposed implementation by you.

2023-12-20 00:14 UTC, closed without merging